//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COID_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class index_table
    {
        public int id { get; set; }
        public int value { get; set; }
    }
}
