//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COID_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_detail
    {
        public int menuId { get; set; }
        public string productID { get; set; }
        public double price { get; set; }
    
        public virtual menu menu { get; set; }
    }
}
