//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COID_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public string id { get; set; }
        public string orderID { get; set; }
        public string productID { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public double total_price { get; set; }
    
        public virtual order order { get; set; }
    }
}
