//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COID_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderSystemEntities : DbContext
    {
        public OrderSystemEntities()
            : base("name=OrderSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<balance> balances { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<combo> comboes { get; set; }
        public virtual DbSet<food> foods { get; set; }
        public virtual DbSet<food_combo> food_combo { get; set; }
        public virtual DbSet<index_table> index_table { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<menu_detail> menu_detail { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<service_time> service_time { get; set; }
        public virtual DbSet<time_menu> time_menu { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
